name: Run LinkedIn Scraping Script

on:
  workflow_dispatch:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run LinkedIn Scraping Script
      env:
        RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
      run: |
        python linkedin_scraping.py
