name: Run LinkedIn Scraping Script

on:
  workflow_dispatch:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run LinkedIn Scraping Script
      env:
        RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
      run: |
        python linkedin_scrapping.py
    - name: List job-postings folder
      run: ls -R job-postings || echo "job-postings folder not found"
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add job-postings
        git commit -m "Add job postings generated by script"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

